name: Deploy akvo34 to test environment

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-test
  cancel-in-progress: false

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/test-reusable.yml # Calls the reusable test workflow
    secrets: inherit

  deploy:
    name: Deploy to test environment
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          path: composite-actions
          ref: 0.0.10

      - name: Update App
        uses: ./composite-actions/.github/actions/ssh-command
        with:
          server-ip:  ${{ secrets.SERVER_IP }}
          server-ssh-port:  ${{ secrets.SERVER_SSH_PORT }}
          server-ssh-secret-key:  ${{ secrets.SERVER_SSH_SECRET_KEY }}
          server-ssh-user:  ${{ secrets.SERVER_SSH_USER }}
          command: ${{ vars.COMMAND }} 